FROM maven:3.9-eclipse-temurin-25 AS plugin-build

WORKDIR /workspace

ARG APP_VERSION=1.4.0

COPY pom.xml .
COPY src ./src

RUN mvn -q -Drevision="${APP_VERSION}" package

FROM itzg/minecraft-server:java25

COPY --from=plugin-build /workspace/target/MinecraftCustomUtilities.jar /plugins/MinecraftCustomUtilities.jar
